# Generated by Django 3.1.3 on 2020-11-09 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_auto_20201109_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=100, unique=True, verbose_name='Contexto')),
            ],
        ),
    ]
