# Generated by Django 3.1.3 on 2020-11-09 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0006_definition'),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='words.category', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='definition',
            name='context',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='words.context', verbose_name='Contexto'),
        ),
        migrations.AddField(
            model_name='definition',
            name='example_eng',
            field=models.TextField(blank=True, null=True, verbose_name='Ejemplo en ingles'),
        ),
        migrations.AddField(
            model_name='definition',
            name='example_spa',
            field=models.TextField(blank=True, null=True, verbose_name='Ejemplo en español'),
        ),
        migrations.AlterField(
            model_name='definition',
            name='meaning',
            field=models.CharField(max_length=150, verbose_name='Significado'),
        ),
    ]
